openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about fruits"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:

    Fruit:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
        weight:
          type: "number"
        description:
          type: "string"
        image_name:
          type: "string"

  parameters:
    fruit_id:
      name: "fruit_id"
      description: "ID of the fruit to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /fruits:
    get:
      operationId: "fruits.read_all"
      tags:
        - "Fruits"
      summary: "Read the list of fruits"
      responses:
        "200":
          description: "Successfully read fruits list"
    post:
      operationId: "fruits.create"
      tags:
        - Fruits
      summary: "Create a fruit"
      requestBody:
        x-body-name: "fruit"
        description: "Fruit to create"
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fruit"
      responses:
        "201":
          description: "Successfully created fruit"
  /fruits/{fruit_id}:
    get:
      operationId: "fruits.read_one"
      tags:
        - Fruits 
      summary: "Read one fruit"
      parameters:
        - $ref: "#/components/parameters/fruit_id"
      responses:
        "200":
          description: "Successfully read fruit"
    put:
      tags:
        - Fruits 
      operationId: "fruits.update"
      summary: "Update a fruit"
      parameters:
        - $ref: "#/components/parameters/fruit_id"
      responses:
        "200":
          description: "Successfully updated fruit"
      requestBody:
        x-body-name: "fruit"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fruit"
    delete:
      tags:
        - Fruits
      operationId: "fruits.delete"
      summary: "Delete a fruit"
      parameters:
        - $ref: "#/components/parameters/fruit_id"
      responses:
        "204":
          description: "Successfully deleted fruit"
  /upload:
    post:
      operationId: "upload.upload"
      tags:
        - Fruit
      summary: "Upload a fruit image"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "201":
          description: "Successfully uploaded fruit image"

